// Generated by src/gen/dev/comboSearch.test.ts (COMBO_SEARCH=1) and checked by src/gen/dev/trialVerify.test.ts
// (COMBO_VERIFY=1): the combo trials of every robot. Each step is a move (animation id) and the ticks after the step
// before landed (the first step: after the start, or after the jump) at which the search entered it; `distance` is
// where the robots stood, `window` the narrowest timing window in ticks, `damage` what it does to the standard dummy
// (Jaguar), and `fails` the robots it does not work against as the dummy.
export interface TrialCombo {
  steps: [move: number, delay: number][];
  distance: number;
  jump: boolean;
  damage: number;
  window: number;
  fails: number[];
}

export const COMBO_TRIALS: Record<number, TrialCombo[]> = {
  0: [
    { steps: [[33, 0], [41, 11]], distance: 40, jump: false, damage: 46, window: 5, fails: [1] },
    { steps: [[33, 0], [23, 13], [16, 14]], distance: 40, jump: false, damage: 53, window: 5, fails: [8] },
    { steps: [[43, 18], [33, 4], [41, 11]], distance: 116, jump: true, damage: 67, window: 5, fails: [] },
  ],
  1: [
    { steps: [[15, 0], [15, 5]], distance: 40, jump: false, damage: 22, window: 4, fails: [] },
    { steps: [[18, 0], [15, 7], [42, 3]], distance: 40, jump: false, damage: 47, window: 3, fails: [3] },
    { steps: [[46, 20], [36, 5], [36, 7]], distance: 116, jump: true, damage: 55, window: 3, fails: [6] },
    { steps: [[68, 21], [15, 6], [42, 3]], distance: 116, jump: true, damage: 51, window: 3, fails: [] },
  ],
  2: [
    { steps: [[41, 0], [16, 9]], distance: 40, jump: false, damage: 45, window: 3, fails: [] },
    { steps: [[41, 0], [17, 9]], distance: 40, jump: false, damage: 45, window: 3, fails: [] },
    { steps: [[43, 19], [29, 4], [23, 9]], distance: 116, jump: true, damage: 56, window: 5, fails: [] },
    { steps: [[41, 0], [23, 8], [23, 5]], distance: 40, jump: false, damage: 35, window: 2, fails: [] },
    { steps: [[43, 19], [35, 5], [17, 5]], distance: 116, jump: true, damage: 56, window: 2, fails: [7] },
  ],
  3: [
    { steps: [[30, 0], [42, 8]], distance: 40, jump: false, damage: 37, window: 6, fails: [] },
    { steps: [[30, 0], [20, 9]], distance: 40, jump: false, damage: 60, window: 4, fails: [] },
    { steps: [[34, 22], [16, 5], [20, 15]], distance: 116, jump: true, damage: 67, window: 8, fails: [] },
    { steps: [[34, 22], [41, 2], [20, 16]], distance: 116, jump: true, damage: 77, window: 3, fails: [] },
    { steps: [[19, 0], [18, 6], [18, 4]], distance: 40, jump: false, damage: 29, window: 2, fails: [3] },
    { steps: [[30, 0], [27, 9], [20, 8]], distance: 40, jump: false, damage: 90, window: 2, fails: [7, 9] },
  ],
  4: [
    { steps: [[25, 0], [23, 10]], distance: 72, jump: false, damage: 39, window: 8, fails: [] },
    { steps: [[41, 0], [23, 3]], distance: 40, jump: false, damage: 21, window: 4, fails: [] },
    { steps: [[25, 0], [23, 10], [35, 13]], distance: 72, jump: false, damage: 65, window: 8, fails: [] },
    { steps: [[25, 0], [41, 10], [34, 18]], distance: 40, jump: false, damage: 73, window: 7, fails: [] },
    { steps: [[25, 0], [41, 10], [35, 18]], distance: 40, jump: false, damage: 68, window: 7, fails: [] },
    { steps: [[44, 18], [43, 5], [43, 5]], distance: 96, jump: true, damage: 35, window: 5, fails: [] },
  ],
  5: [
    { steps: [[18, 0], [22, 6]], distance: 40, jump: false, damage: 38, window: 6, fails: [] },
    { steps: [[18, 0], [23, 6]], distance: 40, jump: false, damage: 38, window: 6, fails: [] },
    { steps: [[43, 21], [31, 4], [22, 5]], distance: 96, jump: true, damage: 51, window: 5, fails: [] },
    { steps: [[18, 0], [15, 6], [22, 5]], distance: 40, jump: false, damage: 49, window: 4, fails: [] },
    { steps: [[18, 0], [15, 6], [23, 5]], distance: 40, jump: false, damage: 49, window: 4, fails: [] },
    { steps: [[43, 21], [42, 4], [42, 7]], distance: 96, jump: true, damage: 59, window: 3, fails: [7] },
  ],
  6: [
    { steps: [[43, 20], [30, 5]], distance: 116, jump: true, damage: 40, window: 7, fails: [] },
    { steps: [[23, 0], [16, 9]], distance: 40, jump: false, damage: 26, window: 3, fails: [] },
    { steps: [[43, 20], [32, 4], [27, 8]], distance: 116, jump: true, damage: 77, window: 4, fails: [2, 7] },
  ],
  7: [
    { steps: [[25, 0], [42, 8]], distance: 40, jump: false, damage: 39, window: 5, fails: [] },
    { steps: [[25, 0], [15, 9]], distance: 40, jump: false, damage: 39, window: 3, fails: [] },
    { steps: [[42, 0], [31, 2]], distance: 40, jump: false, damage: 35, window: 2, fails: [] },
    { steps: [[44, 20], [42, 5], [31, 2]], distance: 96, jump: true, damage: 56, window: 2, fails: [] },
  ],
  8: [
    { steps: [[42, 0], [42, 4]], distance: 40, jump: false, damage: 14, window: 5, fails: [] },
    { steps: [[43, 15], [42, 7], [42, 4]], distance: 96, jump: true, damage: 35, window: 6, fails: [7] },
    { steps: [[21, 0], [15, 10], [21, 14]], distance: 40, jump: false, damage: 59, window: 2, fails: [8] },
    { steps: [[43, 21], [23, 5], [21, 5]], distance: 116, jump: true, damage: 58, window: 2, fails: [] },
  ],
  9: [
    { steps: [[41, 0], [15, 6]], distance: 56, jump: false, damage: 28, window: 5, fails: [] },
    { steps: [[43, 18], [42, 5], [42, 4]], distance: 96, jump: true, damage: 43, window: 3, fails: [3, 7] },
    { steps: [[41, 0], [30, 7], [33, 6]], distance: 40, jump: false, damage: 57, window: 2, fails: [] },
    { steps: [[43, 18], [19, 5], [17, 6]], distance: 96, jump: true, damage: 64, window: 2, fails: [] },
  ],
  10: [
    { steps: [[16, 0], [43, 12]], distance: 40, jump: false, damage: 51, window: 7, fails: [] },
    { steps: [[45, 16], [18, 6], [43, 7]], distance: 116, jump: true, damage: 65, window: 7, fails: [] },
    { steps: [[16, 0], [21, 12], [16, 14]], distance: 40, jump: false, damage: 68, window: 6, fails: [] },
    { steps: [[16, 0], [15, 12], [16, 15]], distance: 40, jump: false, damage: 67, window: 6, fails: [] },
    { steps: [[34, 18], [43, 3], [43, 9]], distance: 116, jump: true, damage: 84, window: 5, fails: [7] },
  ],
  11: [
    { steps: [[43, 15], [22, 6]], distance: 96, jump: true, damage: 28, window: 9, fails: [] },
    { steps: [[43, 15], [42, 5]], distance: 96, jump: true, damage: 28, window: 9, fails: [] },
    { steps: [[33, 0], [16, 6]], distance: 40, jump: false, damage: 51, window: 2, fails: [] },
  ],
  12: [
    { steps: [[34, 7], [22, 7]], distance: 96, jump: true, damage: 26, window: 6, fails: [3] },
    { steps: [[34, 10], [22, 8], [23, 5]], distance: 116, jump: true, damage: 35, window: 4, fails: [] },
  ],
  13: [
    { steps: [[43, 18], [42, 5]], distance: 96, jump: true, damage: 28, window: 9, fails: [] },
    { steps: [[33, 0], [30, 8]], distance: 40, jump: false, damage: 46, window: 6, fails: [] },
    { steps: [[33, 0], [15, 6]], distance: 40, jump: false, damage: 35, window: 2, fails: [2, 4] },
    { steps: [[33, 0], [15, 6], [15, 21]], distance: 40, jump: false, damage: 51, window: 2, fails: [2, 4] },
  ],
  14: [
    { steps: [[33, 0], [41, 8]], distance: 40, jump: false, damage: 46, window: 9, fails: [] },
    { steps: [[33, 0], [17, 9]], distance: 40, jump: false, damage: 49, window: 7, fails: [] },
    { steps: [[43, 21], [33, 3], [17, 8]], distance: 116, jump: true, damage: 70, window: 3, fails: [3] },
  ],
};

/** The special moves that hit a standing dummy (the special move trials): move id and a distance they hit from. */
export const SPECIAL_TRIALS: Record<number, [move: number, distance: number][]> = {
  0: [[16, 40], [17, 40], [21, 40]],
  1: [[16, 40], [21, 40], [24, 40]],
  2: [[16, 40], [17, 40], [34, 70]],
  3: [[20, 40], [25, 40]],
  4: [[22, 40], [23, 40], [34, 40], [35, 40]],
  5: [[22, 40], [23, 40]],
  6: [[17, 40], [19, 40], [21, 40], [22, 40]],
  7: [[21, 40], [26, 40], [27, 40]],
  8: [[21, 40], [22, 40]],
  9: [[18, 70], [23, 40]],
  10: [[16, 40], [22, 40], [31, 40]],
  11: [[15, 40], [16, 40], [17, 40]],
  12: [[15, 40], [16, 40]],
  13: [[15, 40], [17, 40]],
  14: [[15, 40], [17, 40]],
};
